aws_region = "eu-west-2"
az_count = 2
app_port = 8080
fargate_cpu = 256
fargate_memory = 512
app_image = "janakerman/exemplar-service:latest"
app_count = 2
route53_zone_id="ZWHX1EKRNI0U3"
route53_record_name="exemplar-service.janakerman.co.uk"